version: "3.8"

services:
  memory-api:
    build:
      context: https://github.com/sumrendra/memory-api.git
    container_name: memory-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://admin:epaps0991g@192.168.1.4:5432/appdb
      - EMBEDDING_PROVIDER=huggingface
      - VECTOR_DIM=768
      - PYTHONUNBUFFERED=1
    # Simplified startup
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8081"]
    # More lenient health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s
    networks:
      - memory-network

  neurochat-ui:
    build:
      context: https://github.com/sumrendra/memory-api.git
      dockerfile: Dockerfile.streamlit
    container_name: neurochat-ui
    restart: unless-stopped
    ports:
      - "8502:8502"
    environment:
      - MEMORY_API_BASE=http://memory-api:8081
      - LM_STUDIO_API=http://192.168.1.14:1234/v1/chat/completions
    # Remove strict dependency for now
    depends_on:
      - memory-api
    networks:
      - memory-network

networks:
  memory-network:
    driver: bridge