version: "3.8"

services:
  pgvector:
    image: ankane/pgvector:latest
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: change-me
    volumes:
      - pgvector-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgvector-data:
